## PPO parameters
# model_root: "./log_results/1/2024-11-14_13-42-07/eval/model"
max_episode_steps: 512

## iCub class parameters
# test_model: False
render_cameras: ["front_cam",] #["front_cam","head_cam"]
record_video: False
done_if_joints_out_of_limits: False
xml_model_path: "../models/icub_visuomanip_ikin_limits.xml"
print_done_info: True
icub_observation_space:
  - "joints"
  - "joints_vel"
  - "cartesian"
  - "object_pose"
icub_action_space:
  - "joints"
obs_camera: "head_cam_track_hand"
objects:
  - "005_tomato_soup_can"
use_table: False
# task: "refine_grasp"
training_components:
  - "torso_pitch"
  - "torso_yaw"
  - "torso_roll"
  - "r_arm"
joints_margin: 0.0
fixed_initial_pos: True
objects_positions:
  - -0.3
  - 0.05
  - 1.009
objects_quaternions:
  - 1.0
  - 0
  - 0
  - 0
feature_extractor_model_name: "MAE"
track_object: True
eef_name: "r_hand_dh_frame"
max_delta_qpos: 0.05
max_delta_cartesian_rot: 0.01
max_delta_cartesian_pos: 0.002
eval_dir: "./log_results/1/2024-11-21_00-00-00/videos"
ik_components:
  - "torso_pitch"
  - "torso_yaw"
  - "torso_roll"
  - "r_arm"
training_device: "cpu"
cartesian_components:
 - "all_ypr"
# net_arch:
#   - 2048
#   - 2048
distanced_superq_grasp_pose: False #True
ik_solver: "ikin"
randomly_move_objects: False
limit_torso_pitch_ikin: True
approach_in_reset_model: True