project: "rl-example"
program: main.py
method: bayes
metric:
  name: mean_reward_test
  goal: maximize
parameters:
  alpha:
    min: 0.1
    max: 1
  gamma:
    min: 0.1
    max: 1
  epsilon:
    min: 0.01
    max: 0.1
